/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_snail_audio_AudioDevice */

#ifndef _Included_com_snail_audio_AudioDevice
#define _Included_com_snail_audio_AudioDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_audioengine_audio_AudioDevice
 * Method:    RecordDataIsAvailable
 * Signature: (J[BIZ)V
 */
JNIEXPORT void JNICALL Java_com_audioengine_audio_AudioDevice_RecordDataIsAvailable
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_audioengine_audio_AudioDevice
 * Method:    NeedMorePlayData
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_com_audioengine_audio_AudioDevice_NeedMorePlayData
  (JNIEnv *, jobject, jlong, jint);

JNIEXPORT void JNICALL Java_com_audioengine_audio_AudioDevice_CacheDirectBufferAddress
( JNIEnv *env, jobject, jlong ins, jobject byte_buffer, jobject ply_byte_buffer );



#ifdef __cplusplus
}
#endif
#endif
