// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "user_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace audio_engine {
class LoginRequestDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<LoginRequest>
     _instance;
} _LoginRequest_default_instance_;
class LoginResponseDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<LoginResponse>
     _instance;
} _LoginResponse_default_instance_;
class LogoutRequstDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<LogoutRequst>
     _instance;
} _LogoutRequst_default_instance_;
class LogoutResponseDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<LogoutResponse>
     _instance;
} _LogoutResponse_default_instance_;
class LoginNotifyDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<LoginNotify>
     _instance;
} _LoginNotify_default_instance_;
class RAUserMessageDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<RAUserMessage>
     _instance;
} _RAUserMessage_default_instance_;

namespace protobuf_user_5fservice_2eproto {

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _LoginRequest_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_LoginRequest_default_instance_);_LoginResponse_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_LoginResponse_default_instance_);_LogoutRequst_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_LogoutRequst_default_instance_);_LogoutResponse_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_LogoutResponse_default_instance_);_LoginNotify_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_LoginNotify_default_instance_);_RAUserMessage_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_RAUserMessage_default_instance_);_RAUserMessage_default_instance_._instance.get_mutable()->login_requst_ = const_cast< ::audio_engine::LoginRequest*>(
      ::audio_engine::LoginRequest::internal_default_instance());
  _RAUserMessage_default_instance_._instance.get_mutable()->login_response_ = const_cast< ::audio_engine::LoginResponse*>(
      ::audio_engine::LoginResponse::internal_default_instance());
  _RAUserMessage_default_instance_._instance.get_mutable()->logout_requst_ = const_cast< ::audio_engine::LogoutRequst*>(
      ::audio_engine::LogoutRequst::internal_default_instance());
  _RAUserMessage_default_instance_._instance.get_mutable()->logout_response_ = const_cast< ::audio_engine::LogoutResponse*>(
      ::audio_engine::LogoutResponse::internal_default_instance());
  _RAUserMessage_default_instance_._instance.get_mutable()->login_notify_ = const_cast< ::audio_engine::LoginNotify*>(
      ::audio_engine::LoginNotify::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}

}  // namespace protobuf_user_5fservice_2eproto

bool RAMSG_IsValid(int value) {
  switch (value) {
    case 0:
    case 257:
    case 258:
    case 259:
    case 260:
    case 261:
      return true;
    default:
      return false;
  }
}

bool DEVICE_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 8:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LoginRequest::kUseridFieldNumber;
const int LoginRequest::kUsernameFieldNumber;
const int LoginRequest::kDevtypeFieldNumber;
const int LoginRequest::kExtendsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LoginRequest::LoginRequest()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_user_5fservice_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:audio_engine.LoginRequest)
}
LoginRequest::LoginRequest(const LoginRequest& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  userid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.userid().size() > 0) {
    userid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.userid_);
  }
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.username().size() > 0) {
    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
  extends_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.extends().size() > 0) {
    extends_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.extends_);
  }
  devtype_ = from.devtype_;
  // @@protoc_insertion_point(copy_constructor:audio_engine.LoginRequest)
}

void LoginRequest::SharedCtor() {
  userid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  extends_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  devtype_ = 0;
  _cached_size_ = 0;
}

LoginRequest::~LoginRequest() {
  // @@protoc_insertion_point(destructor:audio_engine.LoginRequest)
  SharedDtor();
}

void LoginRequest::SharedDtor() {
  userid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  username_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  extends_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LoginRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const LoginRequest& LoginRequest::default_instance() {
  protobuf_user_5fservice_2eproto::InitDefaults();
  return *internal_default_instance();
}

LoginRequest* LoginRequest::New(::google::protobuf::Arena* arena) const {
  LoginRequest* n = new LoginRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LoginRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:audio_engine.LoginRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  userid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  extends_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  devtype_ = 0;
  _internal_metadata_.Clear();
}

bool LoginRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::NewPermanentCallback(&_internal_metadata_,
          &::google::protobuf::internal::InternalMetadataWithArenaLite::
              mutable_unknown_fields));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:audio_engine.LoginRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string userid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_userid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->userid().data(), static_cast<int>(this->userid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "audio_engine.LoginRequest.userid"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string username = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->username().data(), static_cast<int>(this->username().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "audio_engine.LoginRequest.username"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .audio_engine.DEVICE_TYPE devtype = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_devtype(static_cast< ::audio_engine::DEVICE_TYPE >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string extends = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_extends()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->extends().data(), static_cast<int>(this->extends().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "audio_engine.LoginRequest.extends"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:audio_engine.LoginRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:audio_engine.LoginRequest)
  return false;
#undef DO_
}

void LoginRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:audio_engine.LoginRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string userid = 1;
  if (this->userid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->userid().data(), static_cast<int>(this->userid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "audio_engine.LoginRequest.userid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->userid(), output);
  }

  // string username = 2;
  if (this->username().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->username().data(), static_cast<int>(this->username().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "audio_engine.LoginRequest.username");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->username(), output);
  }

  // .audio_engine.DEVICE_TYPE devtype = 3;
  if (this->devtype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->devtype(), output);
  }

  // string extends = 4;
  if (this->extends().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->extends().data(), static_cast<int>(this->extends().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "audio_engine.LoginRequest.extends");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->extends(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:audio_engine.LoginRequest)
}

size_t LoginRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:audio_engine.LoginRequest)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string userid = 1;
  if (this->userid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->userid());
  }

  // string username = 2;
  if (this->username().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->username());
  }

  // string extends = 4;
  if (this->extends().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->extends());
  }

  // .audio_engine.DEVICE_TYPE devtype = 3;
  if (this->devtype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->devtype());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LoginRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const LoginRequest*>(&from));
}

void LoginRequest::MergeFrom(const LoginRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:audio_engine.LoginRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.userid().size() > 0) {

    userid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.userid_);
  }
  if (from.username().size() > 0) {

    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
  if (from.extends().size() > 0) {

    extends_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.extends_);
  }
  if (from.devtype() != 0) {
    set_devtype(from.devtype());
  }
}

void LoginRequest::CopyFrom(const LoginRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:audio_engine.LoginRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginRequest::IsInitialized() const {
  return true;
}

void LoginRequest::Swap(LoginRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LoginRequest::InternalSwap(LoginRequest* other) {
  using std::swap;
  userid_.Swap(&other->userid_);
  username_.Swap(&other->username_);
  extends_.Swap(&other->extends_);
  swap(devtype_, other->devtype_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string LoginRequest::GetTypeName() const {
  return "audio_engine.LoginRequest";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LoginRequest

// string userid = 1;
void LoginRequest::clear_userid() {
  userid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginRequest::userid() const {
  // @@protoc_insertion_point(field_get:audio_engine.LoginRequest.userid)
  return userid_.GetNoArena();
}
void LoginRequest::set_userid(const ::std::string& value) {
  
  userid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:audio_engine.LoginRequest.userid)
}
#if LANG_CXX11
void LoginRequest::set_userid(::std::string&& value) {
  
  userid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:audio_engine.LoginRequest.userid)
}
#endif
void LoginRequest::set_userid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  userid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:audio_engine.LoginRequest.userid)
}
void LoginRequest::set_userid(const char* value, size_t size) {
  
  userid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:audio_engine.LoginRequest.userid)
}
::std::string* LoginRequest::mutable_userid() {
  
  // @@protoc_insertion_point(field_mutable:audio_engine.LoginRequest.userid)
  return userid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginRequest::release_userid() {
  // @@protoc_insertion_point(field_release:audio_engine.LoginRequest.userid)
  
  return userid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequest::set_allocated_userid(::std::string* userid) {
  if (userid != NULL) {
    
  } else {
    
  }
  userid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), userid);
  // @@protoc_insertion_point(field_set_allocated:audio_engine.LoginRequest.userid)
}

// string username = 2;
void LoginRequest::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginRequest::username() const {
  // @@protoc_insertion_point(field_get:audio_engine.LoginRequest.username)
  return username_.GetNoArena();
}
void LoginRequest::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:audio_engine.LoginRequest.username)
}
#if LANG_CXX11
void LoginRequest::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:audio_engine.LoginRequest.username)
}
#endif
void LoginRequest::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:audio_engine.LoginRequest.username)
}
void LoginRequest::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:audio_engine.LoginRequest.username)
}
::std::string* LoginRequest::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:audio_engine.LoginRequest.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginRequest::release_username() {
  // @@protoc_insertion_point(field_release:audio_engine.LoginRequest.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequest::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:audio_engine.LoginRequest.username)
}

// .audio_engine.DEVICE_TYPE devtype = 3;
void LoginRequest::clear_devtype() {
  devtype_ = 0;
}
::audio_engine::DEVICE_TYPE LoginRequest::devtype() const {
  // @@protoc_insertion_point(field_get:audio_engine.LoginRequest.devtype)
  return static_cast< ::audio_engine::DEVICE_TYPE >(devtype_);
}
void LoginRequest::set_devtype(::audio_engine::DEVICE_TYPE value) {
  
  devtype_ = value;
  // @@protoc_insertion_point(field_set:audio_engine.LoginRequest.devtype)
}

// string extends = 4;
void LoginRequest::clear_extends() {
  extends_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginRequest::extends() const {
  // @@protoc_insertion_point(field_get:audio_engine.LoginRequest.extends)
  return extends_.GetNoArena();
}
void LoginRequest::set_extends(const ::std::string& value) {
  
  extends_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:audio_engine.LoginRequest.extends)
}
#if LANG_CXX11
void LoginRequest::set_extends(::std::string&& value) {
  
  extends_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:audio_engine.LoginRequest.extends)
}
#endif
void LoginRequest::set_extends(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  extends_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:audio_engine.LoginRequest.extends)
}
void LoginRequest::set_extends(const char* value, size_t size) {
  
  extends_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:audio_engine.LoginRequest.extends)
}
::std::string* LoginRequest::mutable_extends() {
  
  // @@protoc_insertion_point(field_mutable:audio_engine.LoginRequest.extends)
  return extends_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginRequest::release_extends() {
  // @@protoc_insertion_point(field_release:audio_engine.LoginRequest.extends)
  
  return extends_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequest::set_allocated_extends(::std::string* extends) {
  if (extends != NULL) {
    
  } else {
    
  }
  extends_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), extends);
  // @@protoc_insertion_point(field_set_allocated:audio_engine.LoginRequest.extends)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LoginResponse::kUseridFieldNumber;
const int LoginResponse::kResultFieldNumber;
const int LoginResponse::kTokenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LoginResponse::LoginResponse()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_user_5fservice_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:audio_engine.LoginResponse)
}
LoginResponse::LoginResponse(const LoginResponse& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  userid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.userid().size() > 0) {
    userid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.userid_);
  }
  ::memcpy(&token_, &from.token_,
    static_cast<size_t>(reinterpret_cast<char*>(&result_) -
    reinterpret_cast<char*>(&token_)) + sizeof(result_));
  // @@protoc_insertion_point(copy_constructor:audio_engine.LoginResponse)
}

void LoginResponse::SharedCtor() {
  userid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&token_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&result_) -
      reinterpret_cast<char*>(&token_)) + sizeof(result_));
  _cached_size_ = 0;
}

LoginResponse::~LoginResponse() {
  // @@protoc_insertion_point(destructor:audio_engine.LoginResponse)
  SharedDtor();
}

void LoginResponse::SharedDtor() {
  userid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LoginResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const LoginResponse& LoginResponse::default_instance() {
  protobuf_user_5fservice_2eproto::InitDefaults();
  return *internal_default_instance();
}

LoginResponse* LoginResponse::New(::google::protobuf::Arena* arena) const {
  LoginResponse* n = new LoginResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LoginResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:audio_engine.LoginResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  userid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&token_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&result_) -
      reinterpret_cast<char*>(&token_)) + sizeof(result_));
  _internal_metadata_.Clear();
}

bool LoginResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::NewPermanentCallback(&_internal_metadata_,
          &::google::protobuf::internal::InternalMetadataWithArenaLite::
              mutable_unknown_fields));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:audio_engine.LoginResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string userid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_userid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->userid().data(), static_cast<int>(this->userid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "audio_engine.LoginResponse.userid"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 result = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 token = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &token_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:audio_engine.LoginResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:audio_engine.LoginResponse)
  return false;
#undef DO_
}

void LoginResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:audio_engine.LoginResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string userid = 1;
  if (this->userid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->userid().data(), static_cast<int>(this->userid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "audio_engine.LoginResponse.userid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->userid(), output);
  }

  // int32 result = 2;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->result(), output);
  }

  // int64 token = 3;
  if (this->token() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->token(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:audio_engine.LoginResponse)
}

size_t LoginResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:audio_engine.LoginResponse)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string userid = 1;
  if (this->userid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->userid());
  }

  // int64 token = 3;
  if (this->token() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->token());
  }

  // int32 result = 2;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->result());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LoginResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const LoginResponse*>(&from));
}

void LoginResponse::MergeFrom(const LoginResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:audio_engine.LoginResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.userid().size() > 0) {

    userid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.userid_);
  }
  if (from.token() != 0) {
    set_token(from.token());
  }
  if (from.result() != 0) {
    set_result(from.result());
  }
}

void LoginResponse::CopyFrom(const LoginResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:audio_engine.LoginResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginResponse::IsInitialized() const {
  return true;
}

void LoginResponse::Swap(LoginResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LoginResponse::InternalSwap(LoginResponse* other) {
  using std::swap;
  userid_.Swap(&other->userid_);
  swap(token_, other->token_);
  swap(result_, other->result_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string LoginResponse::GetTypeName() const {
  return "audio_engine.LoginResponse";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LoginResponse

// string userid = 1;
void LoginResponse::clear_userid() {
  userid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginResponse::userid() const {
  // @@protoc_insertion_point(field_get:audio_engine.LoginResponse.userid)
  return userid_.GetNoArena();
}
void LoginResponse::set_userid(const ::std::string& value) {
  
  userid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:audio_engine.LoginResponse.userid)
}
#if LANG_CXX11
void LoginResponse::set_userid(::std::string&& value) {
  
  userid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:audio_engine.LoginResponse.userid)
}
#endif
void LoginResponse::set_userid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  userid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:audio_engine.LoginResponse.userid)
}
void LoginResponse::set_userid(const char* value, size_t size) {
  
  userid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:audio_engine.LoginResponse.userid)
}
::std::string* LoginResponse::mutable_userid() {
  
  // @@protoc_insertion_point(field_mutable:audio_engine.LoginResponse.userid)
  return userid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginResponse::release_userid() {
  // @@protoc_insertion_point(field_release:audio_engine.LoginResponse.userid)
  
  return userid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginResponse::set_allocated_userid(::std::string* userid) {
  if (userid != NULL) {
    
  } else {
    
  }
  userid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), userid);
  // @@protoc_insertion_point(field_set_allocated:audio_engine.LoginResponse.userid)
}

// int32 result = 2;
void LoginResponse::clear_result() {
  result_ = 0;
}
::google::protobuf::int32 LoginResponse::result() const {
  // @@protoc_insertion_point(field_get:audio_engine.LoginResponse.result)
  return result_;
}
void LoginResponse::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:audio_engine.LoginResponse.result)
}

// int64 token = 3;
void LoginResponse::clear_token() {
  token_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 LoginResponse::token() const {
  // @@protoc_insertion_point(field_get:audio_engine.LoginResponse.token)
  return token_;
}
void LoginResponse::set_token(::google::protobuf::int64 value) {
  
  token_ = value;
  // @@protoc_insertion_point(field_set:audio_engine.LoginResponse.token)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LogoutRequst::kTokenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LogoutRequst::LogoutRequst()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_user_5fservice_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:audio_engine.LogoutRequst)
}
LogoutRequst::LogoutRequst(const LogoutRequst& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  token_ = from.token_;
  // @@protoc_insertion_point(copy_constructor:audio_engine.LogoutRequst)
}

void LogoutRequst::SharedCtor() {
  token_ = GOOGLE_LONGLONG(0);
  _cached_size_ = 0;
}

LogoutRequst::~LogoutRequst() {
  // @@protoc_insertion_point(destructor:audio_engine.LogoutRequst)
  SharedDtor();
}

void LogoutRequst::SharedDtor() {
}

void LogoutRequst::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const LogoutRequst& LogoutRequst::default_instance() {
  protobuf_user_5fservice_2eproto::InitDefaults();
  return *internal_default_instance();
}

LogoutRequst* LogoutRequst::New(::google::protobuf::Arena* arena) const {
  LogoutRequst* n = new LogoutRequst;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LogoutRequst::Clear() {
// @@protoc_insertion_point(message_clear_start:audio_engine.LogoutRequst)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  token_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool LogoutRequst::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::NewPermanentCallback(&_internal_metadata_,
          &::google::protobuf::internal::InternalMetadataWithArenaLite::
              mutable_unknown_fields));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:audio_engine.LogoutRequst)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 token = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &token_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:audio_engine.LogoutRequst)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:audio_engine.LogoutRequst)
  return false;
#undef DO_
}

void LogoutRequst::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:audio_engine.LogoutRequst)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 token = 1;
  if (this->token() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->token(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:audio_engine.LogoutRequst)
}

size_t LogoutRequst::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:audio_engine.LogoutRequst)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // int64 token = 1;
  if (this->token() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->token());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LogoutRequst::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const LogoutRequst*>(&from));
}

void LogoutRequst::MergeFrom(const LogoutRequst& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:audio_engine.LogoutRequst)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.token() != 0) {
    set_token(from.token());
  }
}

void LogoutRequst::CopyFrom(const LogoutRequst& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:audio_engine.LogoutRequst)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogoutRequst::IsInitialized() const {
  return true;
}

void LogoutRequst::Swap(LogoutRequst* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LogoutRequst::InternalSwap(LogoutRequst* other) {
  using std::swap;
  swap(token_, other->token_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string LogoutRequst::GetTypeName() const {
  return "audio_engine.LogoutRequst";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LogoutRequst

// int64 token = 1;
void LogoutRequst::clear_token() {
  token_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 LogoutRequst::token() const {
  // @@protoc_insertion_point(field_get:audio_engine.LogoutRequst.token)
  return token_;
}
void LogoutRequst::set_token(::google::protobuf::int64 value) {
  
  token_ = value;
  // @@protoc_insertion_point(field_set:audio_engine.LogoutRequst.token)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LogoutResponse::kTokenFieldNumber;
const int LogoutResponse::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LogoutResponse::LogoutResponse()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_user_5fservice_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:audio_engine.LogoutResponse)
}
LogoutResponse::LogoutResponse(const LogoutResponse& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&token_, &from.token_,
    static_cast<size_t>(reinterpret_cast<char*>(&status_) -
    reinterpret_cast<char*>(&token_)) + sizeof(status_));
  // @@protoc_insertion_point(copy_constructor:audio_engine.LogoutResponse)
}

void LogoutResponse::SharedCtor() {
  ::memset(&token_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&token_)) + sizeof(status_));
  _cached_size_ = 0;
}

LogoutResponse::~LogoutResponse() {
  // @@protoc_insertion_point(destructor:audio_engine.LogoutResponse)
  SharedDtor();
}

void LogoutResponse::SharedDtor() {
}

void LogoutResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const LogoutResponse& LogoutResponse::default_instance() {
  protobuf_user_5fservice_2eproto::InitDefaults();
  return *internal_default_instance();
}

LogoutResponse* LogoutResponse::New(::google::protobuf::Arena* arena) const {
  LogoutResponse* n = new LogoutResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LogoutResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:audio_engine.LogoutResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&token_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&token_)) + sizeof(status_));
  _internal_metadata_.Clear();
}

bool LogoutResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::NewPermanentCallback(&_internal_metadata_,
          &::google::protobuf::internal::InternalMetadataWithArenaLite::
              mutable_unknown_fields));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:audio_engine.LogoutResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 token = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &token_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 status = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &status_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:audio_engine.LogoutResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:audio_engine.LogoutResponse)
  return false;
#undef DO_
}

void LogoutResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:audio_engine.LogoutResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 token = 1;
  if (this->token() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->token(), output);
  }

  // int64 status = 2;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->status(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:audio_engine.LogoutResponse)
}

size_t LogoutResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:audio_engine.LogoutResponse)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // int64 token = 1;
  if (this->token() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->token());
  }

  // int64 status = 2;
  if (this->status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->status());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LogoutResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const LogoutResponse*>(&from));
}

void LogoutResponse::MergeFrom(const LogoutResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:audio_engine.LogoutResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.token() != 0) {
    set_token(from.token());
  }
  if (from.status() != 0) {
    set_status(from.status());
  }
}

void LogoutResponse::CopyFrom(const LogoutResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:audio_engine.LogoutResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogoutResponse::IsInitialized() const {
  return true;
}

void LogoutResponse::Swap(LogoutResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LogoutResponse::InternalSwap(LogoutResponse* other) {
  using std::swap;
  swap(token_, other->token_);
  swap(status_, other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string LogoutResponse::GetTypeName() const {
  return "audio_engine.LogoutResponse";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LogoutResponse

// int64 token = 1;
void LogoutResponse::clear_token() {
  token_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 LogoutResponse::token() const {
  // @@protoc_insertion_point(field_get:audio_engine.LogoutResponse.token)
  return token_;
}
void LogoutResponse::set_token(::google::protobuf::int64 value) {
  
  token_ = value;
  // @@protoc_insertion_point(field_set:audio_engine.LogoutResponse.token)
}

// int64 status = 2;
void LogoutResponse::clear_status() {
  status_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 LogoutResponse::status() const {
  // @@protoc_insertion_point(field_get:audio_engine.LogoutResponse.status)
  return status_;
}
void LogoutResponse::set_status(::google::protobuf::int64 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:audio_engine.LogoutResponse.status)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LoginNotify::kUseridFieldNumber;
const int LoginNotify::kUsernameFieldNumber;
const int LoginNotify::kExtendFieldNumber;
const int LoginNotify::kDevtypeFieldNumber;
const int LoginNotify::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LoginNotify::LoginNotify()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_user_5fservice_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:audio_engine.LoginNotify)
}
LoginNotify::LoginNotify(const LoginNotify& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  userid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.userid().size() > 0) {
    userid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.userid_);
  }
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.username().size() > 0) {
    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
  extend_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.extend().size() > 0) {
    extend_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.extend_);
  }
  ::memcpy(&devtype_, &from.devtype_,
    static_cast<size_t>(reinterpret_cast<char*>(&status_) -
    reinterpret_cast<char*>(&devtype_)) + sizeof(status_));
  // @@protoc_insertion_point(copy_constructor:audio_engine.LoginNotify)
}

void LoginNotify::SharedCtor() {
  userid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  extend_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&devtype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&devtype_)) + sizeof(status_));
  _cached_size_ = 0;
}

LoginNotify::~LoginNotify() {
  // @@protoc_insertion_point(destructor:audio_engine.LoginNotify)
  SharedDtor();
}

void LoginNotify::SharedDtor() {
  userid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  username_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  extend_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LoginNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const LoginNotify& LoginNotify::default_instance() {
  protobuf_user_5fservice_2eproto::InitDefaults();
  return *internal_default_instance();
}

LoginNotify* LoginNotify::New(::google::protobuf::Arena* arena) const {
  LoginNotify* n = new LoginNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LoginNotify::Clear() {
// @@protoc_insertion_point(message_clear_start:audio_engine.LoginNotify)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  userid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  extend_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&devtype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&devtype_)) + sizeof(status_));
  _internal_metadata_.Clear();
}

bool LoginNotify::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::NewPermanentCallback(&_internal_metadata_,
          &::google::protobuf::internal::InternalMetadataWithArenaLite::
              mutable_unknown_fields));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:audio_engine.LoginNotify)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string userid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_userid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->userid().data(), static_cast<int>(this->userid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "audio_engine.LoginNotify.userid"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string username = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->username().data(), static_cast<int>(this->username().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "audio_engine.LoginNotify.username"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string extend = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_extend()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->extend().data(), static_cast<int>(this->extend().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "audio_engine.LoginNotify.extend"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .audio_engine.DEVICE_TYPE devtype = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_devtype(static_cast< ::audio_engine::DEVICE_TYPE >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 status = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &status_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:audio_engine.LoginNotify)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:audio_engine.LoginNotify)
  return false;
#undef DO_
}

void LoginNotify::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:audio_engine.LoginNotify)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string userid = 1;
  if (this->userid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->userid().data(), static_cast<int>(this->userid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "audio_engine.LoginNotify.userid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->userid(), output);
  }

  // string username = 2;
  if (this->username().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->username().data(), static_cast<int>(this->username().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "audio_engine.LoginNotify.username");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->username(), output);
  }

  // string extend = 3;
  if (this->extend().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->extend().data(), static_cast<int>(this->extend().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "audio_engine.LoginNotify.extend");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->extend(), output);
  }

  // .audio_engine.DEVICE_TYPE devtype = 4;
  if (this->devtype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->devtype(), output);
  }

  // int32 status = 5;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->status(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:audio_engine.LoginNotify)
}

size_t LoginNotify::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:audio_engine.LoginNotify)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string userid = 1;
  if (this->userid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->userid());
  }

  // string username = 2;
  if (this->username().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->username());
  }

  // string extend = 3;
  if (this->extend().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->extend());
  }

  // .audio_engine.DEVICE_TYPE devtype = 4;
  if (this->devtype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->devtype());
  }

  // int32 status = 5;
  if (this->status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->status());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LoginNotify::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const LoginNotify*>(&from));
}

void LoginNotify::MergeFrom(const LoginNotify& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:audio_engine.LoginNotify)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.userid().size() > 0) {

    userid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.userid_);
  }
  if (from.username().size() > 0) {

    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
  if (from.extend().size() > 0) {

    extend_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.extend_);
  }
  if (from.devtype() != 0) {
    set_devtype(from.devtype());
  }
  if (from.status() != 0) {
    set_status(from.status());
  }
}

void LoginNotify::CopyFrom(const LoginNotify& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:audio_engine.LoginNotify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginNotify::IsInitialized() const {
  return true;
}

void LoginNotify::Swap(LoginNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LoginNotify::InternalSwap(LoginNotify* other) {
  using std::swap;
  userid_.Swap(&other->userid_);
  username_.Swap(&other->username_);
  extend_.Swap(&other->extend_);
  swap(devtype_, other->devtype_);
  swap(status_, other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string LoginNotify::GetTypeName() const {
  return "audio_engine.LoginNotify";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LoginNotify

// string userid = 1;
void LoginNotify::clear_userid() {
  userid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginNotify::userid() const {
  // @@protoc_insertion_point(field_get:audio_engine.LoginNotify.userid)
  return userid_.GetNoArena();
}
void LoginNotify::set_userid(const ::std::string& value) {
  
  userid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:audio_engine.LoginNotify.userid)
}
#if LANG_CXX11
void LoginNotify::set_userid(::std::string&& value) {
  
  userid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:audio_engine.LoginNotify.userid)
}
#endif
void LoginNotify::set_userid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  userid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:audio_engine.LoginNotify.userid)
}
void LoginNotify::set_userid(const char* value, size_t size) {
  
  userid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:audio_engine.LoginNotify.userid)
}
::std::string* LoginNotify::mutable_userid() {
  
  // @@protoc_insertion_point(field_mutable:audio_engine.LoginNotify.userid)
  return userid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginNotify::release_userid() {
  // @@protoc_insertion_point(field_release:audio_engine.LoginNotify.userid)
  
  return userid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginNotify::set_allocated_userid(::std::string* userid) {
  if (userid != NULL) {
    
  } else {
    
  }
  userid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), userid);
  // @@protoc_insertion_point(field_set_allocated:audio_engine.LoginNotify.userid)
}

// string username = 2;
void LoginNotify::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginNotify::username() const {
  // @@protoc_insertion_point(field_get:audio_engine.LoginNotify.username)
  return username_.GetNoArena();
}
void LoginNotify::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:audio_engine.LoginNotify.username)
}
#if LANG_CXX11
void LoginNotify::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:audio_engine.LoginNotify.username)
}
#endif
void LoginNotify::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:audio_engine.LoginNotify.username)
}
void LoginNotify::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:audio_engine.LoginNotify.username)
}
::std::string* LoginNotify::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:audio_engine.LoginNotify.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginNotify::release_username() {
  // @@protoc_insertion_point(field_release:audio_engine.LoginNotify.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginNotify::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:audio_engine.LoginNotify.username)
}

// string extend = 3;
void LoginNotify::clear_extend() {
  extend_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginNotify::extend() const {
  // @@protoc_insertion_point(field_get:audio_engine.LoginNotify.extend)
  return extend_.GetNoArena();
}
void LoginNotify::set_extend(const ::std::string& value) {
  
  extend_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:audio_engine.LoginNotify.extend)
}
#if LANG_CXX11
void LoginNotify::set_extend(::std::string&& value) {
  
  extend_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:audio_engine.LoginNotify.extend)
}
#endif
void LoginNotify::set_extend(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  extend_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:audio_engine.LoginNotify.extend)
}
void LoginNotify::set_extend(const char* value, size_t size) {
  
  extend_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:audio_engine.LoginNotify.extend)
}
::std::string* LoginNotify::mutable_extend() {
  
  // @@protoc_insertion_point(field_mutable:audio_engine.LoginNotify.extend)
  return extend_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginNotify::release_extend() {
  // @@protoc_insertion_point(field_release:audio_engine.LoginNotify.extend)
  
  return extend_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginNotify::set_allocated_extend(::std::string* extend) {
  if (extend != NULL) {
    
  } else {
    
  }
  extend_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), extend);
  // @@protoc_insertion_point(field_set_allocated:audio_engine.LoginNotify.extend)
}

// .audio_engine.DEVICE_TYPE devtype = 4;
void LoginNotify::clear_devtype() {
  devtype_ = 0;
}
::audio_engine::DEVICE_TYPE LoginNotify::devtype() const {
  // @@protoc_insertion_point(field_get:audio_engine.LoginNotify.devtype)
  return static_cast< ::audio_engine::DEVICE_TYPE >(devtype_);
}
void LoginNotify::set_devtype(::audio_engine::DEVICE_TYPE value) {
  
  devtype_ = value;
  // @@protoc_insertion_point(field_set:audio_engine.LoginNotify.devtype)
}

// int32 status = 5;
void LoginNotify::clear_status() {
  status_ = 0;
}
::google::protobuf::int32 LoginNotify::status() const {
  // @@protoc_insertion_point(field_get:audio_engine.LoginNotify.status)
  return status_;
}
void LoginNotify::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:audio_engine.LoginNotify.status)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RAUserMessage::kCmdFieldNumber;
const int RAUserMessage::kLoginRequstFieldNumber;
const int RAUserMessage::kLoginResponseFieldNumber;
const int RAUserMessage::kLogoutRequstFieldNumber;
const int RAUserMessage::kLogoutResponseFieldNumber;
const int RAUserMessage::kLoginNotifyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RAUserMessage::RAUserMessage()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_user_5fservice_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:audio_engine.RAUserMessage)
}
RAUserMessage::RAUserMessage(const RAUserMessage& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_login_requst()) {
    login_requst_ = new ::audio_engine::LoginRequest(*from.login_requst_);
  } else {
    login_requst_ = NULL;
  }
  if (from.has_login_response()) {
    login_response_ = new ::audio_engine::LoginResponse(*from.login_response_);
  } else {
    login_response_ = NULL;
  }
  if (from.has_logout_requst()) {
    logout_requst_ = new ::audio_engine::LogoutRequst(*from.logout_requst_);
  } else {
    logout_requst_ = NULL;
  }
  if (from.has_logout_response()) {
    logout_response_ = new ::audio_engine::LogoutResponse(*from.logout_response_);
  } else {
    logout_response_ = NULL;
  }
  if (from.has_login_notify()) {
    login_notify_ = new ::audio_engine::LoginNotify(*from.login_notify_);
  } else {
    login_notify_ = NULL;
  }
  cmd_ = from.cmd_;
  // @@protoc_insertion_point(copy_constructor:audio_engine.RAUserMessage)
}

void RAUserMessage::SharedCtor() {
  ::memset(&login_requst_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cmd_) -
      reinterpret_cast<char*>(&login_requst_)) + sizeof(cmd_));
  _cached_size_ = 0;
}

RAUserMessage::~RAUserMessage() {
  // @@protoc_insertion_point(destructor:audio_engine.RAUserMessage)
  SharedDtor();
}

void RAUserMessage::SharedDtor() {
  if (this != internal_default_instance()) delete login_requst_;
  if (this != internal_default_instance()) delete login_response_;
  if (this != internal_default_instance()) delete logout_requst_;
  if (this != internal_default_instance()) delete logout_response_;
  if (this != internal_default_instance()) delete login_notify_;
}

void RAUserMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const RAUserMessage& RAUserMessage::default_instance() {
  protobuf_user_5fservice_2eproto::InitDefaults();
  return *internal_default_instance();
}

RAUserMessage* RAUserMessage::New(::google::protobuf::Arena* arena) const {
  RAUserMessage* n = new RAUserMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RAUserMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:audio_engine.RAUserMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && login_requst_ != NULL) {
    delete login_requst_;
  }
  login_requst_ = NULL;
  if (GetArenaNoVirtual() == NULL && login_response_ != NULL) {
    delete login_response_;
  }
  login_response_ = NULL;
  if (GetArenaNoVirtual() == NULL && logout_requst_ != NULL) {
    delete logout_requst_;
  }
  logout_requst_ = NULL;
  if (GetArenaNoVirtual() == NULL && logout_response_ != NULL) {
    delete logout_response_;
  }
  logout_response_ = NULL;
  if (GetArenaNoVirtual() == NULL && login_notify_ != NULL) {
    delete login_notify_;
  }
  login_notify_ = NULL;
  cmd_ = 0;
  _internal_metadata_.Clear();
}

bool RAUserMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::NewPermanentCallback(&_internal_metadata_,
          &::google::protobuf::internal::InternalMetadataWithArenaLite::
              mutable_unknown_fields));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:audio_engine.RAUserMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .audio_engine.RAMSG cmd = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_cmd(static_cast< ::audio_engine::RAMSG >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .audio_engine.LoginRequest login_requst = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_login_requst()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .audio_engine.LoginResponse login_response = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_login_response()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .audio_engine.LogoutRequst logout_requst = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_logout_requst()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .audio_engine.LogoutResponse logout_response = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_logout_response()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .audio_engine.LoginNotify login_notify = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_login_notify()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:audio_engine.RAUserMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:audio_engine.RAUserMessage)
  return false;
#undef DO_
}

void RAUserMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:audio_engine.RAUserMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .audio_engine.RAMSG cmd = 1;
  if (this->cmd() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->cmd(), output);
  }

  // .audio_engine.LoginRequest login_requst = 2;
  if (this->has_login_requst()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, *this->login_requst_, output);
  }

  // .audio_engine.LoginResponse login_response = 3;
  if (this->has_login_response()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, *this->login_response_, output);
  }

  // .audio_engine.LogoutRequst logout_requst = 4;
  if (this->has_logout_requst()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, *this->logout_requst_, output);
  }

  // .audio_engine.LogoutResponse logout_response = 5;
  if (this->has_logout_response()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      5, *this->logout_response_, output);
  }

  // .audio_engine.LoginNotify login_notify = 6;
  if (this->has_login_notify()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      6, *this->login_notify_, output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:audio_engine.RAUserMessage)
}

size_t RAUserMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:audio_engine.RAUserMessage)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // .audio_engine.LoginRequest login_requst = 2;
  if (this->has_login_requst()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->login_requst_);
  }

  // .audio_engine.LoginResponse login_response = 3;
  if (this->has_login_response()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->login_response_);
  }

  // .audio_engine.LogoutRequst logout_requst = 4;
  if (this->has_logout_requst()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->logout_requst_);
  }

  // .audio_engine.LogoutResponse logout_response = 5;
  if (this->has_logout_response()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->logout_response_);
  }

  // .audio_engine.LoginNotify login_notify = 6;
  if (this->has_login_notify()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->login_notify_);
  }

  // .audio_engine.RAMSG cmd = 1;
  if (this->cmd() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->cmd());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RAUserMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const RAUserMessage*>(&from));
}

void RAUserMessage::MergeFrom(const RAUserMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:audio_engine.RAUserMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_login_requst()) {
    mutable_login_requst()->::audio_engine::LoginRequest::MergeFrom(from.login_requst());
  }
  if (from.has_login_response()) {
    mutable_login_response()->::audio_engine::LoginResponse::MergeFrom(from.login_response());
  }
  if (from.has_logout_requst()) {
    mutable_logout_requst()->::audio_engine::LogoutRequst::MergeFrom(from.logout_requst());
  }
  if (from.has_logout_response()) {
    mutable_logout_response()->::audio_engine::LogoutResponse::MergeFrom(from.logout_response());
  }
  if (from.has_login_notify()) {
    mutable_login_notify()->::audio_engine::LoginNotify::MergeFrom(from.login_notify());
  }
  if (from.cmd() != 0) {
    set_cmd(from.cmd());
  }
}

void RAUserMessage::CopyFrom(const RAUserMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:audio_engine.RAUserMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RAUserMessage::IsInitialized() const {
  return true;
}

void RAUserMessage::Swap(RAUserMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RAUserMessage::InternalSwap(RAUserMessage* other) {
  using std::swap;
  swap(login_requst_, other->login_requst_);
  swap(login_response_, other->login_response_);
  swap(logout_requst_, other->logout_requst_);
  swap(logout_response_, other->logout_response_);
  swap(login_notify_, other->login_notify_);
  swap(cmd_, other->cmd_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::std::string RAUserMessage::GetTypeName() const {
  return "audio_engine.RAUserMessage";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RAUserMessage

// .audio_engine.RAMSG cmd = 1;
void RAUserMessage::clear_cmd() {
  cmd_ = 0;
}
::audio_engine::RAMSG RAUserMessage::cmd() const {
  // @@protoc_insertion_point(field_get:audio_engine.RAUserMessage.cmd)
  return static_cast< ::audio_engine::RAMSG >(cmd_);
}
void RAUserMessage::set_cmd(::audio_engine::RAMSG value) {
  
  cmd_ = value;
  // @@protoc_insertion_point(field_set:audio_engine.RAUserMessage.cmd)
}

// .audio_engine.LoginRequest login_requst = 2;
bool RAUserMessage::has_login_requst() const {
  return this != internal_default_instance() && login_requst_ != NULL;
}
void RAUserMessage::clear_login_requst() {
  if (GetArenaNoVirtual() == NULL && login_requst_ != NULL) delete login_requst_;
  login_requst_ = NULL;
}
const ::audio_engine::LoginRequest& RAUserMessage::login_requst() const {
  const ::audio_engine::LoginRequest* p = login_requst_;
  // @@protoc_insertion_point(field_get:audio_engine.RAUserMessage.login_requst)
  return p != NULL ? *p : *reinterpret_cast<const ::audio_engine::LoginRequest*>(
      &::audio_engine::_LoginRequest_default_instance_);
}
::audio_engine::LoginRequest* RAUserMessage::mutable_login_requst() {
  
  if (login_requst_ == NULL) {
    login_requst_ = new ::audio_engine::LoginRequest;
  }
  // @@protoc_insertion_point(field_mutable:audio_engine.RAUserMessage.login_requst)
  return login_requst_;
}
::audio_engine::LoginRequest* RAUserMessage::release_login_requst() {
  // @@protoc_insertion_point(field_release:audio_engine.RAUserMessage.login_requst)
  
  ::audio_engine::LoginRequest* temp = login_requst_;
  login_requst_ = NULL;
  return temp;
}
void RAUserMessage::set_allocated_login_requst(::audio_engine::LoginRequest* login_requst) {
  delete login_requst_;
  login_requst_ = login_requst;
  if (login_requst) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:audio_engine.RAUserMessage.login_requst)
}

// .audio_engine.LoginResponse login_response = 3;
bool RAUserMessage::has_login_response() const {
  return this != internal_default_instance() && login_response_ != NULL;
}
void RAUserMessage::clear_login_response() {
  if (GetArenaNoVirtual() == NULL && login_response_ != NULL) delete login_response_;
  login_response_ = NULL;
}
const ::audio_engine::LoginResponse& RAUserMessage::login_response() const {
  const ::audio_engine::LoginResponse* p = login_response_;
  // @@protoc_insertion_point(field_get:audio_engine.RAUserMessage.login_response)
  return p != NULL ? *p : *reinterpret_cast<const ::audio_engine::LoginResponse*>(
      &::audio_engine::_LoginResponse_default_instance_);
}
::audio_engine::LoginResponse* RAUserMessage::mutable_login_response() {
  
  if (login_response_ == NULL) {
    login_response_ = new ::audio_engine::LoginResponse;
  }
  // @@protoc_insertion_point(field_mutable:audio_engine.RAUserMessage.login_response)
  return login_response_;
}
::audio_engine::LoginResponse* RAUserMessage::release_login_response() {
  // @@protoc_insertion_point(field_release:audio_engine.RAUserMessage.login_response)
  
  ::audio_engine::LoginResponse* temp = login_response_;
  login_response_ = NULL;
  return temp;
}
void RAUserMessage::set_allocated_login_response(::audio_engine::LoginResponse* login_response) {
  delete login_response_;
  login_response_ = login_response;
  if (login_response) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:audio_engine.RAUserMessage.login_response)
}

// .audio_engine.LogoutRequst logout_requst = 4;
bool RAUserMessage::has_logout_requst() const {
  return this != internal_default_instance() && logout_requst_ != NULL;
}
void RAUserMessage::clear_logout_requst() {
  if (GetArenaNoVirtual() == NULL && logout_requst_ != NULL) delete logout_requst_;
  logout_requst_ = NULL;
}
const ::audio_engine::LogoutRequst& RAUserMessage::logout_requst() const {
  const ::audio_engine::LogoutRequst* p = logout_requst_;
  // @@protoc_insertion_point(field_get:audio_engine.RAUserMessage.logout_requst)
  return p != NULL ? *p : *reinterpret_cast<const ::audio_engine::LogoutRequst*>(
      &::audio_engine::_LogoutRequst_default_instance_);
}
::audio_engine::LogoutRequst* RAUserMessage::mutable_logout_requst() {
  
  if (logout_requst_ == NULL) {
    logout_requst_ = new ::audio_engine::LogoutRequst;
  }
  // @@protoc_insertion_point(field_mutable:audio_engine.RAUserMessage.logout_requst)
  return logout_requst_;
}
::audio_engine::LogoutRequst* RAUserMessage::release_logout_requst() {
  // @@protoc_insertion_point(field_release:audio_engine.RAUserMessage.logout_requst)
  
  ::audio_engine::LogoutRequst* temp = logout_requst_;
  logout_requst_ = NULL;
  return temp;
}
void RAUserMessage::set_allocated_logout_requst(::audio_engine::LogoutRequst* logout_requst) {
  delete logout_requst_;
  logout_requst_ = logout_requst;
  if (logout_requst) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:audio_engine.RAUserMessage.logout_requst)
}

// .audio_engine.LogoutResponse logout_response = 5;
bool RAUserMessage::has_logout_response() const {
  return this != internal_default_instance() && logout_response_ != NULL;
}
void RAUserMessage::clear_logout_response() {
  if (GetArenaNoVirtual() == NULL && logout_response_ != NULL) delete logout_response_;
  logout_response_ = NULL;
}
const ::audio_engine::LogoutResponse& RAUserMessage::logout_response() const {
  const ::audio_engine::LogoutResponse* p = logout_response_;
  // @@protoc_insertion_point(field_get:audio_engine.RAUserMessage.logout_response)
  return p != NULL ? *p : *reinterpret_cast<const ::audio_engine::LogoutResponse*>(
      &::audio_engine::_LogoutResponse_default_instance_);
}
::audio_engine::LogoutResponse* RAUserMessage::mutable_logout_response() {
  
  if (logout_response_ == NULL) {
    logout_response_ = new ::audio_engine::LogoutResponse;
  }
  // @@protoc_insertion_point(field_mutable:audio_engine.RAUserMessage.logout_response)
  return logout_response_;
}
::audio_engine::LogoutResponse* RAUserMessage::release_logout_response() {
  // @@protoc_insertion_point(field_release:audio_engine.RAUserMessage.logout_response)
  
  ::audio_engine::LogoutResponse* temp = logout_response_;
  logout_response_ = NULL;
  return temp;
}
void RAUserMessage::set_allocated_logout_response(::audio_engine::LogoutResponse* logout_response) {
  delete logout_response_;
  logout_response_ = logout_response;
  if (logout_response) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:audio_engine.RAUserMessage.logout_response)
}

// .audio_engine.LoginNotify login_notify = 6;
bool RAUserMessage::has_login_notify() const {
  return this != internal_default_instance() && login_notify_ != NULL;
}
void RAUserMessage::clear_login_notify() {
  if (GetArenaNoVirtual() == NULL && login_notify_ != NULL) delete login_notify_;
  login_notify_ = NULL;
}
const ::audio_engine::LoginNotify& RAUserMessage::login_notify() const {
  const ::audio_engine::LoginNotify* p = login_notify_;
  // @@protoc_insertion_point(field_get:audio_engine.RAUserMessage.login_notify)
  return p != NULL ? *p : *reinterpret_cast<const ::audio_engine::LoginNotify*>(
      &::audio_engine::_LoginNotify_default_instance_);
}
::audio_engine::LoginNotify* RAUserMessage::mutable_login_notify() {
  
  if (login_notify_ == NULL) {
    login_notify_ = new ::audio_engine::LoginNotify;
  }
  // @@protoc_insertion_point(field_mutable:audio_engine.RAUserMessage.login_notify)
  return login_notify_;
}
::audio_engine::LoginNotify* RAUserMessage::release_login_notify() {
  // @@protoc_insertion_point(field_release:audio_engine.RAUserMessage.login_notify)
  
  ::audio_engine::LoginNotify* temp = login_notify_;
  login_notify_ = NULL;
  return temp;
}
void RAUserMessage::set_allocated_login_notify(::audio_engine::LoginNotify* login_notify) {
  delete login_notify_;
  login_notify_ = login_notify;
  if (login_notify) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:audio_engine.RAUserMessage.login_notify)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace audio_engine

// @@protoc_insertion_point(global_scope)
